---
abstract: 'Combine several images into a CSS sprite'
author:
  - 'Savio Dimatteo <savio@lokku.com>'
build_requires:
  Config::Simple: 0
  Cwd: 0
  File::Basename: 0
  File::Find::Rule: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  File::Touch: 0
  Test::CheckManifest: 0
  Test::File: 1.33
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CSS-SpriteMaker
provides:
  File::CleanupTask:
    file: lib/CSS/SpriteMaker.pm
    version: 0.09
requires:
  Config::Simple: 0
  File::Basename: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  File::Which: 0
  Getopt::Long: 0
  IPC::Run3: 0
  Sort::Key: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
